image: Ubuntu2204

stack: java 11

branches:
  only:
    - main

install:
  - chmod +x gradlew

build: off

services:
  - mysql

before_test:
  - sudo systemctl start mysql
  - mysql -e "CREATE DATABASE IF NOT EXISTS app;"
  - mysql -e "CREATE USER IF NOT EXISTS 'app'@'localhost' IDENTIFIED BY 'pass';"
  - mysql -e "GRANT ALL PRIVILEGES ON app.* TO 'app'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"
  - sleep 10

test_script:
  - ./gradlew test
